"""Demo data for showcasing the portal when MYOB is not configured."""

from datetime import datetime, timedelta, timezone

from app.schemas.order import (
    OrderDetail,
    OrderLineItem,
    OrderStatus,
    OrderSummary,
)

now = datetime.now(timezone.utc)


def _dt(days_offset: int) -> datetime:
    return now + timedelta(days=days_offset)


DEMO_ORDERS: dict[str, OrderDetail] = {
    "SO-001042": OrderDetail(
        order_nbr="SO-001042",
        order_date=_dt(-120),
        customer_id="DEMO",
        customer_name="Demo Customer",
        customer_order_ref="PO-7891",
        description="Stainless Steel Valve Bodies — Batch A",
        overall_status=OrderStatus.SHIPPED,
        total_amount=28750.00,
        estimated_delivery=_dt(-5),
        lines=[
            OrderLineItem(
                line_nbr=1,
                inventory_id="VLV-SS-200",
                description="SS316 Valve Body 2\" 150# RF",
                quantity=50,
                unit_price=350.00,
                line_total=17500.00,
                status=OrderStatus.SHIPPED,
                estimated_delivery=_dt(-10),
                po_order_nbr="PO-002180",
                po_requested_date=_dt(-30),
                received_date=_dt(-15),
                inspected_at=_dt(-12),
                invoiced_at=_dt(-5),
            ),
            OrderLineItem(
                line_nbr=2,
                inventory_id="VLV-SS-300",
                description="SS316 Valve Body 3\" 150# RF",
                quantity=25,
                unit_price=450.00,
                line_total=11250.00,
                status=OrderStatus.SHIPPED,
                estimated_delivery=_dt(-10),
                po_order_nbr="PO-002180",
                po_requested_date=_dt(-30),
                received_date=_dt(-15),
                inspected_at=_dt(-12),
                invoiced_at=_dt(-5),
            ),
        ],
    ),
    "SO-001078": OrderDetail(
        order_nbr="SO-001078",
        order_date=_dt(-90),
        customer_id="DEMO",
        customer_name="Demo Customer",
        customer_order_ref="PO-8023",
        description="Bronze Impellers — Pump Overhaul",
        overall_status=OrderStatus.INSPECTED,
        total_amount=15200.00,
        estimated_delivery=_dt(3),
        lines=[
            OrderLineItem(
                line_nbr=1,
                inventory_id="IMP-BRZ-150",
                description="Bronze Impeller 6\" Dia, 4-Vane",
                quantity=10,
                unit_price=820.00,
                line_total=8200.00,
                status=OrderStatus.INSPECTED,
                estimated_delivery=_dt(-8),
                po_order_nbr="PO-002215",
                po_requested_date=_dt(-20),
                received_date=_dt(-10),
                inspected_at=_dt(-2),
            ),
            OrderLineItem(
                line_nbr=2,
                inventory_id="IMP-BRZ-200",
                description="Bronze Impeller 8\" Dia, 6-Vane",
                quantity=8,
                unit_price=875.00,
                line_total=7000.00,
                status=OrderStatus.INSPECTED,
                estimated_delivery=_dt(-8),
                po_order_nbr="PO-002215",
                po_requested_date=_dt(-20),
                received_date=_dt(-10),
                inspected_at=_dt(-2),
            ),
        ],
    ),
    "SO-001103": OrderDetail(
        order_nbr="SO-001103",
        order_date=_dt(-60),
        customer_id="DEMO",
        customer_name="Demo Customer",
        customer_order_ref="PO-8156",
        description="Cast Iron Flanges — Pipeline Project",
        overall_status=OrderStatus.IN_WAREHOUSE,
        total_amount=9450.00,
        estimated_delivery=_dt(10),
        lines=[
            OrderLineItem(
                line_nbr=1,
                inventory_id="FLG-CI-100",
                description='Ductile Iron Flange 4" PN16',
                quantity=100,
                unit_price=45.00,
                line_total=4500.00,
                status=OrderStatus.IN_WAREHOUSE,
                estimated_delivery=_dt(-5),
                po_order_nbr="PO-002248",
                po_requested_date=_dt(-15),
                received_date=_dt(-3),
            ),
            OrderLineItem(
                line_nbr=2,
                inventory_id="FLG-CI-150",
                description='Ductile Iron Flange 6" PN16',
                quantity=50,
                unit_price=65.00,
                line_total=3250.00,
                status=OrderStatus.IN_WAREHOUSE,
                estimated_delivery=_dt(-5),
                po_order_nbr="PO-002248",
                po_requested_date=_dt(-15),
                received_date=_dt(-3),
            ),
            OrderLineItem(
                line_nbr=3,
                inventory_id="FLG-CI-200",
                description='Ductile Iron Flange 8" PN16',
                quantity=20,
                unit_price=85.00,
                line_total=1700.00,
                status=OrderStatus.IN_WAREHOUSE,
                estimated_delivery=_dt(-5),
                po_order_nbr="PO-002249",
                po_requested_date=_dt(-15),
                received_date=_dt(-4),
            ),
        ],
    ),
    "SO-001125": OrderDetail(
        order_nbr="SO-001125",
        order_date=_dt(-45),
        customer_id="DEMO",
        customer_name="Demo Customer",
        customer_order_ref="PO-8210",
        description="Aluminium Gear Housings",
        overall_status=OrderStatus.IN_TRANSIT,
        total_amount=22800.00,
        estimated_delivery=_dt(18),
        lines=[
            OrderLineItem(
                line_nbr=1,
                inventory_id="GH-AL-500",
                description="Aluminium Gear Housing Assembly, CNC Machined",
                quantity=12,
                unit_price=1900.00,
                line_total=22800.00,
                status=OrderStatus.IN_TRANSIT,
                estimated_delivery=_dt(18),
                po_order_nbr="PO-002267",
            ),
        ],
    ),
    "SO-001148": OrderDetail(
        order_nbr="SO-001148",
        order_date=_dt(-30),
        customer_id="DEMO",
        customer_name="Demo Customer",
        customer_order_ref="PO-8345",
        description="Steel Mounting Brackets — Wind Turbine",
        overall_status=OrderStatus.IN_PRODUCTION,
        total_amount=34500.00,
        estimated_delivery=_dt(35),
        lines=[
            OrderLineItem(
                line_nbr=1,
                inventory_id="BRK-ST-900",
                description="Heavy Duty Steel Mounting Bracket, Galvanised",
                quantity=30,
                unit_price=750.00,
                line_total=22500.00,
                status=OrderStatus.IN_PRODUCTION,
                estimated_delivery=_dt(14),
                po_order_nbr="PO-002290",
                po_requested_date=_dt(14),
            ),
            OrderLineItem(
                line_nbr=2,
                inventory_id="BRK-ST-901",
                description="Adjustment Plate, Galvanised Steel",
                quantity=30,
                unit_price=400.00,
                line_total=12000.00,
                status=OrderStatus.IN_PRODUCTION,
                estimated_delivery=_dt(14),
                po_order_nbr="PO-002290",
                po_requested_date=_dt(14),
            ),
        ],
    ),
    "SO-001167": OrderDetail(
        order_nbr="SO-001167",
        order_date=_dt(-10),
        customer_id="DEMO",
        customer_name="Demo Customer",
        customer_order_ref="PO-8490",
        description="Copper Alloy Bushings — Marine Application",
        overall_status=OrderStatus.WAITING_FOR_PRODUCTION,
        total_amount=18600.00,
        estimated_delivery=_dt(120),
        lines=[
            OrderLineItem(
                line_nbr=1,
                inventory_id="BSH-CU-75",
                description="CuSn10 Bronze Bushing 75mm OD x 55mm ID",
                quantity=40,
                unit_price=285.00,
                line_total=11400.00,
                status=OrderStatus.WAITING_FOR_PRODUCTION,
                estimated_delivery=_dt(120),
                po_order_nbr="PO-002310",
                po_requested_date=_dt(120),
            ),
            OrderLineItem(
                line_nbr=2,
                inventory_id="BSH-CU-100",
                description="CuSn10 Bronze Bushing 100mm OD x 75mm ID",
                quantity=20,
                unit_price=360.00,
                line_total=7200.00,
                status=OrderStatus.WAITING_FOR_PRODUCTION,
                estimated_delivery=_dt(120),
                po_order_nbr="PO-002310",
                po_requested_date=_dt(120),
            ),
        ],
    ),
}


def get_demo_order_summaries() -> list[OrderSummary]:
    summaries = []
    for o in DEMO_ORDERS.values():
        summaries.append(
            OrderSummary(
                order_nbr=o.order_nbr,
                order_date=o.order_date,
                customer_id=o.customer_id,
                customer_name=o.customer_name,
                description=o.description,
                overall_status=o.overall_status,
                total_amount=o.total_amount,
                line_count=len(o.lines),
                estimated_delivery=o.estimated_delivery,
            )
        )
    return summaries


def get_demo_order_detail(order_nbr: str) -> OrderDetail | None:
    return DEMO_ORDERS.get(order_nbr)
